// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiTestRepositories.DatabaseContexts;

namespace RestApiTestEFCore.Migrations
{
    [DbContext(typeof(RestApiTestDataContext))]
    [Migration("20191013115839_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("RestApiTestDomain.Models.RestApi", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("RestApis");
                });
#pragma warning restore 612, 618
        }
    }
}
