// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiTestRepositories.DatabaseContexts;

namespace RestApiTestEFCore.Migrations
{
    [DbContext(typeof(RestApiTestDataContext))]
    [Migration("20191013123816_CreateRestApiTestMigration")]
    partial class CreateRestApiTestMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("RestApiTestDomain.Models.RestApi", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("RestApis");
                });

            modelBuilder.Entity("RestApiTestDomain.Models.RestApiTest", b =>
                {
                    b.Property<long>("RestApiTestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExectedResponseJsonSchema")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .HasColumnType("TEXT");

                    b.HasKey("RestApiTestId");

                    b.ToTable("RestApiTests");
                });
#pragma warning restore 612, 618
        }
    }
}
